baseURL = 'https://example.org/'
languageCode = 'en'
title = 'Agency Template Default'

[taxonomies]
  property = "properties"

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
